SEND_SEVEC:
		SNZB		F_SEND
		JP	    	DATA_BIT0
		SNZB		F_BIT_FIRST
		JP	    	BIT_FIRST
		SZB 		F_BIT_END
		JP	    	BIT_END
		SZB 		F_BIT0
		JP	    	SEND_BIT0
		SZB 		F_BIT1
		JP	    	SEND_BIT1
SEND_SEVEC1:	
		SZINCR		BIT_CONT
		RLCR		DATA
		SNZB		STATUS,C
		JP	    	SEND_SEVEC2
		SETB		DATA,0
		SETB		F_BIT1
		CLR	    	BIT_TIME
		JP	    	SEND_BIT1
SEND_SEVEC2:	
		CLRB		DATA,0
		SETB		F_BIT0
		CLR	    	BIT_TIME
		JP	    	SEND_BIT0
SEND_BIT1:		
		SZINCR		BIT_TIME
		NOP	
		LD	    	A,BIT_TIME
		HSUBIA  	D'5'
		SNZB		STATUS,C
		JP	    	DATA_BIT1
		LD	    	A,BIT_TIME
		NOP	
		HSUBIA  	D'17'
		SNZB		STATUS,C
		JP	    	DATA_BIT0
		CLR  		BIT_TIME
		CLRB		F_BIT1
		LD	    	A,BIT_CONT
		NOP	
		HSUBIA  	D'16';8
		SNZB		STATUS,C
		JP	    	END_SEND_SEVEC
		CLR	    	BIT_CONT
		SETB		OUT_DATA
		SETB		F_BIT_END
		JP	    	END_SEND_SEVEC
SEND_BIT0:		
		SZINCR		BIT_TIME
		NOP	
		LD	    	A,BIT_TIME
		HSUBIA  	D'5'
		SNZB		STATUS,C
		JP	    	DATA_BIT1
		LD	    	A,BIT_TIME
		NOP	
		HSUBIA  	D'9'
		SNZB		STATUS,C
		JP	    	DATA_BIT0
		CLRB		F_BIT0
		CLR	    	BIT_TIME
		LD	    	A,BIT_CONT
		NOP	
		HSUBIA  	D'16';8
		SNZB		STATUS,C
		JP	    	END_SEND_SEVEC
		CLR	    	BIT_CONT
		SETB		OUT_DATA
		SETB		F_BIT_END
		JP	    	END_SEND_SEVEC
BIT_END:	
		SETB		OUT_DATA
		SZINCR		BIT_TIME
		NOP	
		LD	    	A,BIT_TIME
		HSUBIA  	D'5'
		SNZB		STATUS,C
		JP	    	DATA_BIT1
		CLR	    	BIT_TIME
		CLRB		F_BIT_END
	    	CLRB		F_BIT_FIRST
		CLRB		F_SEND
		JP	    	DATA_BIT0
BIT_FIRST:	
		SZINCR		BIT_TIME
		NOP	
		LD  		A,BIT_TIME
		HSUBIA  	D'32'
		SNZB		STATUS,C
		JP	    	DATA_BIT1
		LD	    	A,BIT_TIME
		HSUBIA  	D'49';63
		SNZB		STATUS,C
		JP	    	DATA_BIT0
		CLR	    	BIT_TIME
		SETB		F_BIT_FIRST
		JP	    	DATA_BIT0
DATA_BIT1:	
		SETB		OUT_DATA
		JP	    	END_SEND_SEVEC
DATA_BIT0:
		CLRB		OUT_DATA
END_SEND_SEVEC:
