ZERO_PRC:
			LD		A,ZERO_CNT
			HSUBIA	D'250'
			SNZB	STATUS,C
			SZINCR	ZERO_CNT
			NOP
			SNZB	ZERO_PORT
			JP		ZERO_NPULSE
ZERO_PPULSE:
			SZB		F_ZERO_RISE
			JP		END_ZERO_PRC
			SETB	F_ZERO_RISE
			CLR		ZERO_CNT
			JP		END_ZERO_PRC
ZERO_NPULSE:
			SNZB	F_ZERO_RISE
			JP		END_ZERO_PRC
			CLRB	F_ZERO_RISE
			CLR		ZERO_CNT
			JP		END_ZERO_PRC
END_ZERO_PRC:
